### ISSUE TITLE
AttributeError: 'int' object has no attribute 'item'

### ISSUE THREAD

**Issue by MichaelMonashev** [ProGamerGov/neural-dream#4]
```
~/neural-dream$ python3 neural_dream.py -gpu c -content_image 1/7.jpg -output_image 1/9.jpg -init random -model_file models/nin_imagenet.pth
NIN Architecture Detected
Successfully loaded models/nin_imagenet.pth
conv1: 96 3 11 11
cccp1: 96 96 1 1
cccp2: 96 96 1 1
conv2: 256 96 5 5
cccp3: 256 256 1 1
cccp4: 256 256 1 1
conv3: 384 256 3 3
cccp5: 384 384 1 1
cccp6: 384 384 1 1
conv4-1024: 1024 384 3 3
cccp7-1024: 1024 1024 1 1
cccp8-1024: 1000 1024 1 1
nn.Sequential (
  [input -> (1) -> (2) -> (3) -> (4) -> (5) -> (6) -> (7) -> (8) -> (9) -> (10) -> (11) -> (12) -> (13) -> (14) -> (15) -> (16) -> (17) -> (18) -> (19) -> (20
) -> (21) -> (22) -> (23) -> (24) -> (25) -> (26) -> (27) -> (28) -> (29) -> (30) -> output]
  (1): nn.Jitter
  (2): nn.Conv2d(3 -> 96, 11x11, 4,4, 0,0)
  (3): nn.ReLU
  (4): nn.Conv2d(96 -> 96, 1x1, 1,1, 0,0)
  (5): nn.ReLU
  (6): nn.Conv2d(96 -> 96, 1x1, 1,1, 0,0)
  (7): nn.ReLU
  (8): nn.MaxPool2d(3x3,3,3,2,2,2,2)
  (9): nn.Conv2d(96 -> 256, 5x5, 1,1, 2,2)
  (10): nn.ReLU
  (11): nn.Conv2d(256 -> 256, 1x1, 1,1, 0,0)
  (12): nn.ReLU
  (13): nn.Conv2d(256 -> 256, 1x1, 1,1, 0,0)
  (14): nn.ReLU
  (15): nn.MaxPool2d(3x3,3,3,2,2,2,2)
  (16): nn.Conv2d(256 -> 384, 3x3, 1,1, 1,1)
  (17): nn.ReLU
  (18): nn.Conv2d(384 -> 384, 1x1, 1,1, 0,0)
  (19): nn.ReLU
  (20): nn.Conv2d(384 -> 384, 1x1, 1,1, 0,0)
  (21): nn.ReLU
  (22): nn.MaxPool2d(3x3,3,3,2,2,2,2)
  (23): nn.Dropout
  (24): nn.Conv2d(384 -> 1024, 3x3, 1,1, 1,1)
  (25): nn.ReLU
  (26): nn.Conv2d(1024 -> 1024, 1x1, 1,1, 0,0)
  (27): nn.ReLU
  (28): nn.Conv2d(1024 -> 1000, 1x1, 1,1, 0,0)
  (29): nn.ReLU
  (30): nn.AvgPool2d(6x6,6,6,1,1,1,1)
)
Running optimization with ADAM

Performing 2 octaves with the following image sizes:
  Octave 1 image size: 307x230
  Octave 2 image size: 512x384

Traceback (most recent call last):
  File "neural_dream.py", line 793, in <module>
    main()
  File "neural_dream.py", line 281, in main
    optimizer.step(feval)
  File "/home/xxx/.local/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/xxx/.local/lib/python3.6/site-packages/torch/optim/adam.py", line 62, in step
    loss = closure()
  File "neural_dream.py", line 270, in feval
    total_loss[0] += loss.item()
AttributeError: 'int' object has no attribute 'item'
```

**Comment by ProGamerGov** [comment]
You need to specify one or more of the following NIN layer names with `-dream_layers`:

```
conv1, cccp1, cccp2, conv2, cccp3, cccp4, conv3, cccp5, cccp6, conv4-1024, cccp7-1024, cccp8-1024, relu0, relu1, relu2, relu3, relu5, relu6, relu7, relu8, relu9, relu10, relu11, relu12, pool1, pool2, pool3, pool4, drop
```

You can also add the `-print_layers` flag to your command if you want to see all valid layer name choices for a model.

**Comment by MichaelMonashev** [comment]
It works! Thank you!
