### ISSUE TITLE
AttributeError: 'int' object has no attribute 'to'

### ISSUE THREAD

**Issue by MichaelMonashev** [ProGamerGov/neural-dream#7]
```
~/neural-dream$ python3 neural_dream.py -init random -gpu c -output_image 000.webp -channels 0 -dream_layers inception_3b_5x5 -channel_mode strong
GoogLeNet Architecture Detected
Successfully loaded models/bvlc_googlenet.pth
Setting up dream layer 1: inception_3b_5x5
Running optimization with ADAM

Selected layer channels:
  inception_3b_5x5:  []

Performing 2 octaves with the following image sizes:
  Octave 1 image size: 230x307
  Octave 2 image size: 384x512

Traceback (most recent call last):
  File "neural_dream.py", line 793, in <module>
    main()
  File "neural_dream.py", line 281, in main
    optimizer.step(feval)
  File "/home/xxxx/.local/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/xxxx/.local/lib/python3.6/site-packages/torch/optim/adam.py", line 62, in step
    loss = closure()
  File "neural_dream.py", line 257, in feval
    loss += -mod.loss.to(backward_device)
AttributeError: 'int' object has no attribute 'to'
```

**Comment by ProGamerGov** [comment]
@MichaelMonashev You selected the `0` most strongest most channels, so it's unable to return to return a loss value. When using `-channel_mode strong`, `-channel_mode avg`, or `-channel_mode weak`, only the first value of `-channels` is used, and it's used to determine how many average, weak, or strong channels you want to use.

**Comment by MichaelMonashev** [comment]
Thank you!
